project:
  type: book
  output-dir: _book
  
execute:
  freeze: auto  
  
book:
  google-analytics: "G-3EEM211S00"
  title: "Fitopatometria |> R"
  author: "  - Juan Edwards, Juan Paredes y Bruno Pugliese"
  search: true
  cover-image: cornerstone_hand.png
  
  chapters:
    - index.qmd
    - 1-metricas.qmd
    # - 2-metricas2.qmd
    # - 3-glm.qmd
    # - 4-pliman.qmd
    # - 5-escalaa.qmd
    # - 6-ec50.qmd
    - referencias.qmd

bibliography: references.bib
csl: phytopathology.csl
format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: cosmo
   
  pdf:
    documentclass: scrreprt


