project:
  type: book
  output-dir: _book
  
execute:
  freeze: auto  
  
book:
  
  google-analytics: "G-3EEM211S00"
  title: "Fitopatometria-r"
  author: "Juan Edwards"
  search: true
  cover-image: cornerstone_hand.png
  
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: cosmo
   
  pdf:
    documentclass: scrreprt



